/**
 * Realistic Mock Data for AI Study Buddy (Phase 1)
 */

export const MOCK_USER = {
  id: 'usr_001',
  name: 'Alex Vance',
  email: 'alex.vance@mit.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'student',
  institution: 'Department of Computer Science',
  studyStreakDays: 14,
  quizzesCompleted: 28,
  averageMastery: 78,
};

export const MOCK_COURSES = [
  {
    id: 'course-cs301',
    code: 'CS 301',
    name: 'Distributed Systems & Cloud Computing',
    description: 'Consensus protocols (Raft, Paxos), CAP theorem, vector clocks, and scalable microservice architectures.',
    examDate: '2026-10-15',
    color: '#6366f1',
    progress: 74,
    documentsCount: 6,
    topicsCount: 5,
    lastStudied: 'Today, 2:30 PM',
    topics: [
      {
        id: 'top-1',
        title: 'CAP Theorem & PACELC Trade-offs',
        order: 1,
        mastery: 92,
        status: 'mastered',
        summary: 'Consistency, Availability, and Partition tolerance guarantees under asynchronous network partitions.',
        subtopics: ['Network Partitions', 'Strict vs Eventual Consistency', 'Dynamo-style Quorums'],
      },
      {
        id: 'top-2',
        title: 'Consensus: Raft & Paxos Algorithm',
        order: 2,
        mastery: 65,
        status: 'improving',
        summary: 'Leader election, log replication, safety invariants, and state machine consistency.',
        subtopics: ['Leader Election', 'Log Compaction & Snapshots', 'Split Brain Prevention'],
      },
      {
        id: 'top-3',
        title: 'Logical Time & Vector Clocks',
        order: 3,
        mastery: 42,
        status: 'weak',
        summary: 'Lamport timestamps, causal orderings, and detecting concurrent conflicting updates.',
        subtopics: ['Lamport Clocks', 'Vector Timestamps', 'Matrix Clocks'],
      },
      {
        id: 'top-4',
        title: 'Distributed Transactions & 2PC',
        order: 4,
        mastery: 80,
        status: 'mastered',
        summary: 'Two-phase commit, three-phase commit, and Saga pattern for distributed rollbacks.',
        subtopics: ['Two-Phase Commit', 'Saga Pattern', 'Distributed Locking'],
      },
      {
        id: 'top-5',
        title: 'Gossip Protocols & Failure Detection',
        order: 5,
        mastery: 55,
        status: 'improving',
        summary: 'Epidemic algorithms, phi-accrual failure detection, and cluster membership lists.',
        subtopics: ['SWIM Protocol', 'Phi Accrual Failure Detector', 'Anti-Entropy'],
      },
    ],
  },
  {
    id: 'course-cs420',
    code: 'CS 420',
    name: 'Operating Systems & Concurrency',
    description: 'Kernel internals, virtual memory paging, scheduling algorithms, lock-free synchronization, and file systems.',
    examDate: '2026-11-02',
    color: '#a855f7',
    progress: 58,
    documentsCount: 8,
    topicsCount: 4,
    lastStudied: 'Yesterday',
    topics: [
      {
        id: 'top-os-1',
        title: 'Virtual Memory & Page Replacement',
        order: 1,
        mastery: 70,
        status: 'improving',
        summary: 'Multi-level page tables, TLB shootdowns, LRU and Clock replacement algorithms.',
        subtopics: ['TLB Caches', 'Inverted Page Tables', 'Demand Paging'],
      },
      {
        id: 'top-os-2',
        title: 'Concurrency Primitives & Deadlock',
        order: 2,
        mastery: 35,
        status: 'weak',
        summary: 'Mutexes, semaphores, condition variables, Banker algorithm, and lock inversion.',
        subtopics: ['Banker Algorithm', 'Lock Ordering', 'Futex Implementation'],
      },
      {
        id: 'top-os-3',
        title: 'CPU Scheduling & CFS',
        order: 3,
        mastery: 88,
        status: 'mastered',
        summary: 'Completely Fair Scheduler (CFS), multi-core affinity, and real-time scheduling guarantees.',
        subtopics: ['CFS Red-Black Trees', 'Work Stealing', 'Priority Inversion'],
      },
      {
        id: 'top-os-4',
        title: 'File Systems & Journaling',
        order: 4,
        mastery: 60,
        status: 'improving',
        summary: 'Ext4 journaling, inodes, copy-on-write (Btrfs/ZFS), and crash consistency.',
        subtopics: ['Inodes & Dentries', 'Write-Ahead Journaling', 'FSCK recovery'],
      },
    ],
  },
  {
    id: 'course-ai502',
    code: 'AI 502',
    name: 'Neural Networks & Deep Learning',
    description: 'Transformer architectures, multi-head attention, backpropagation mathematics, and diffusion models.',
    examDate: '2026-12-10',
    color: '#06b6d4',
    progress: 82,
    documentsCount: 11,
    topicsCount: 4,
    lastStudied: '3 days ago',
    topics: [
      {
        id: 'top-ai-1',
        title: 'Backpropagation & Computational Graphs',
        order: 1,
        mastery: 95,
        status: 'mastered',
        summary: 'Reverse-mode automatic differentiation, Jacobian matrices, and vanishing gradients.',
        subtopics: ['Chain Rule Derivations', 'Gradient Clipping', 'Optimizer Dynamics (AdamW)'],
      },
      {
        id: 'top-ai-2',
        title: 'Transformers & Self-Attention',
        order: 2,
        mastery: 85,
        status: 'mastered',
        summary: 'Scaled dot-product attention, positional embeddings (RoPE), and KV-caching.',
        subtopics: ['Scaled Dot-Product Attention', 'Rotary Positional Embeddings', 'FlashAttention'],
      },
      {
        id: 'top-ai-3',
        title: 'RAG & Vector Retrieval',
        order: 3,
        mastery: 90,
        status: 'mastered',
        summary: 'Dense embeddings, HNSW vector indexing, reciprocal rank fusion, and context windows.',
        subtopics: ['Cosine Similarity vs Dot Product', 'HNSW Graph Search', 'Context Window Re-ranking'],
      },
      {
        id: 'top-ai-4',
        title: 'Diffusion Models & Score Matching',
        order: 4,
        mastery: 45,
        status: 'weak',
        summary: 'Forward and reverse diffusion SDEs, DDPM, DDIM sampling, and classifier-free guidance.',
        subtopics: ['Forward Gaussian Noise', 'Score Matching', 'Classifier-Free Guidance'],
      },
    ],
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: 'doc-01',
    courseId: 'course-cs301',
    courseName: 'Distributed Systems',
    fileName: 'Lecture-04-Raft-Consensus.pdf',
    fileType: 'PDF',
    size: '3.4 MB',
    uploadedAt: '2026-08-28',
    status: 'indexed',
    chunksCount: 48,
    embeddingsCount: 48,
  },
  {
    id: 'doc-02',
    courseId: 'course-cs301',
    courseName: 'Distributed Systems',
    fileName: 'Syllabus-Fall-2026.docx',
    fileType: 'DOCX',
    size: '420 KB',
    uploadedAt: '2026-08-20',
    status: 'indexed',
    chunksCount: 12,
    embeddingsCount: 12,
  },
  {
    id: 'doc-03',
    courseId: 'course-cs420',
    courseName: 'Operating Systems',
    fileName: 'Operating-Systems-Concurrency-Notes.pdf',
    fileType: 'PDF',
    size: '5.1 MB',
    uploadedAt: '2026-08-25',
    status: 'indexed',
    chunksCount: 82,
    embeddingsCount: 82,
  },
  {
    id: 'doc-04',
    courseId: 'course-ai502',
    courseName: 'Neural Networks',
    fileName: 'Attention-Is-All-You-Need-Annotated.pdf',
    fileType: 'PDF',
    size: '2.8 MB',
    uploadedAt: '2026-09-01',
    status: 'indexed',
    chunksCount: 36,
    embeddingsCount: 36,
  },
  {
    id: 'doc-05',
    courseId: 'course-cs301',
    courseName: 'Distributed Systems',
    fileName: 'Vector-Clocks-Paper-Notes.txt',
    fileType: 'TXT',
    size: '95 KB',
    uploadedAt: '2026-09-03',
    status: 'processing',
    chunksCount: 18,
    embeddingsCount: 12,
  },
];

export const MOCK_RECENT_QUIZZES = [
  {
    id: 'quiz-01',
    courseId: 'course-cs301',
    courseCode: 'CS 301',
    title: 'Raft Consensus & Leader Election Practice',
    questionsCount: 10,
    difficulty: 'Medium',
    score: 80,
    completedAt: 'Yesterday',
    type: 'MCQ & Short Answer',
  },
  {
    id: 'quiz-02',
    courseId: 'course-cs420',
    courseCode: 'CS 420',
    title: 'Deadlock Detection & Concurrency Primitives',
    questionsCount: 8,
    difficulty: 'Hard',
    score: 45,
    completedAt: '2 days ago',
    type: 'MCQ & True/False',
  },
  {
    id: 'quiz-03',
    courseId: 'course-ai502',
    courseCode: 'AI 502',
    title: 'Self-Attention & Positional Encodings Check',
    questionsCount: 12,
    difficulty: 'Medium',
    score: 92,
    completedAt: '4 days ago',
    type: 'MCQ',
  },
];

export const MOCK_STUDY_PLAN_TASKS = [
  {
    id: 'task-1',
    courseCode: 'CS 301',
    courseName: 'Distributed Systems',
    topic: 'Logical Time & Vector Clocks',
    duration: '35 mins',
    activity: 'AI Tutor Deep Dive + Practice Quiz',
    priority: 'high',
    reason: 'Identified as weak topic (42% mastery)',
    status: 'pending',
    scheduledFor: 'Today',
  },
  {
    id: 'task-2',
    courseCode: 'CS 420',
    courseName: 'Operating Systems',
    topic: 'Banker Algorithm & Deadlock Avoidance',
    duration: '25 mins',
    activity: 'ELI10 Concept Simplification',
    priority: 'high',
    reason: 'Last quiz score was 45%',
    status: 'pending',
    scheduledFor: 'Today',
  },
  {
    id: 'task-3',
    courseCode: 'AI 502',
    courseName: 'Neural Networks',
    topic: 'Score Matching in Diffusion Models',
    duration: '40 mins',
    activity: 'Document Note Review & Formula Check',
    priority: 'medium',
    reason: 'Exam in 90 days',
    status: 'upcoming',
    scheduledFor: 'Tomorrow',
  },
];

export const MOCK_WEAK_TOPICS = [
  {
    id: 'weak-1',
    courseCode: 'CS 420',
    topic: 'Concurrency Primitives & Deadlock',
    mastery: 35,
    trend: '-5% last week',
    suggestedAction: 'Take 5-min Hint Mode Quiz',
  },
  {
    id: 'weak-2',
    courseCode: 'CS 301',
    topic: 'Logical Time & Vector Clocks',
    mastery: 42,
    trend: '+4% this week',
    suggestedAction: 'Review Vector Clocks Document Chunks',
  },
  {
    id: 'weak-3',
    courseCode: 'AI 502',
    topic: 'Diffusion Models & Score Matching',
    mastery: 45,
    trend: 'New topic',
    suggestedAction: 'Start ELI10 Tutor Session',
  },
];
