import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Clock, HelpCircle, Layers, Award, Play, CheckCircle2 } from 'lucide-react';
import { quizService } from '../services/quizService';
import Card, { CardHeader, CardTitle, CardContent } from '../../../components/ui/Card';
import Button from '../../../components/ui/Button';
import Badge from '../../../components/ui/Badge';
import Loading from '../../../components/common/Loading';
import ErrorState from '../../../components/common/ErrorState';

export default function QuizDetailPage() {
  const { quizId } = useParams();
  const navigate = useNavigate();

  const [quiz, setQuiz] = useState(null);
  const [loading, setLoading] = useState(true);
  const [startingAttempt, setStartingAttempt] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchQuiz = async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await quizService.getQuizById(quizId);
        setQuiz(data);
      } catch (err) {
        setError(err.message || 'Failed to load quiz details.');
      } finally {
        setLoading(false);
      }
    };

    if (quizId) fetchQuiz();
  }, [quizId]);

  const handleStartAttempt = async () => {
    setStartingAttempt(true);
    try {
      const attempt = await quizService.startAttempt(quizId);
      navigate(`/quizzes/${quizId}/attempt`, {
        state: { attemptId: attempt.attemptId, quiz },
      });
    } catch (err) {
      console.error(err);
      navigate(`/quizzes/${quizId}/attempt`, {
        state: { attemptId: `att-${Date.now()}`, quiz },
      });
    } finally {
      setStartingAttempt(false);
    }
  };

  if (loading) {
    return <Loading message="Preparing quiz details..." fullPage size="lg" />;
  }

  if (error || !quiz) {
    return (
      <ErrorState
        title="Quiz Not Found"
        message={error || 'Could not find the requested practice quiz.'}
        onRetry={() => navigate('/quizzes')}
        retryLabel="Back to Quizzes"
      />
    );
  }

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '24px' }} className="animate-fade-in">
      <button
        onClick={() => navigate(-1)}
        style={{
          background: 'transparent',
          border: 'none',
          color: 'var(--text-secondary)',
          fontSize: '0.85rem',
          cursor: 'pointer',
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          padding: 0,
          fontWeight: 500,
        }}
      >
        <ArrowLeft size={16} /> Back
      </button>

      <Card glass style={{ border: '1px solid var(--border-glow)' }}>
        <CardContent style={{ padding: '36px' }}>
          {/* Header Badges */}
          <div style={{ display: 'flex', gap: '8px', marginBottom: '16px' }}>
            <Badge variant="primary" size="md">
              {quiz.courseCode || 'COURSE'}
            </Badge>
            <Badge
              variant={quiz.difficulty === 'Hard' ? 'danger' : quiz.difficulty === 'Medium' ? 'warning' : 'success'}
              size="md"
            >
              {quiz.difficulty || 'Medium'}
            </Badge>
            <Badge variant="outline" size="md">
              {quiz.type || 'MCQ'}
            </Badge>
          </div>

          <h1 style={{ fontSize: '2rem', fontWeight: 800, margin: '0 0 12px 0', lineHeight: 1.25 }}>
            {quiz.title}
          </h1>

          <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: 1.6, marginBottom: '28px' }}>
            This self-evaluation drill is generated by the Quiz Agent to measure concept retention across your course syllabus. Results and weak topics will be updated on your learning dashboard.
          </p>

          {/* Key Parameters */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: '16px',
              padding: '20px',
              borderRadius: 'var(--radius-lg)',
              backgroundColor: 'var(--bg-elevated)',
              marginBottom: '32px',
            }}
          >
            <div>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Questions</span>
              <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--text-primary)', marginTop: '2px' }}>
                {quiz.questionsCount || quiz.questions?.length || 5} Questions
              </div>
            </div>

            <div>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Time Limit</span>
              <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--primary)', marginTop: '2px' }}>
                {quiz.timeLimitMinutes || 10} Minutes
              </div>
            </div>

            <div>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Topic Focus</span>
              <div style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', marginTop: '4px' }}>
                {quiz.topicName || 'Curriculum Modules'}
              </div>
            </div>
          </div>

          {/* Action Button */}
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '14px' }}>
            <Button variant="ghost" size="lg" onClick={() => navigate(-1)}>
              Cancel
            </Button>

            <Button
              variant="primary"
              size="lg"
              icon={Play}
              loading={startingAttempt}
              onClick={handleStartAttempt}
            >
              Begin Quiz Attempt
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
